//The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

//1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

//Let us list the factors of the first seven triangle numbers:

// 1: 1
// 3: 1,3
// 6: 1,2,3,6
//10: 1,2,5,10
//15: 1,3,5,15
//21: 1,3,7,21
//28: 1,2,4,7,14,28
//We can see that 28 is the first triangle number to have over five divisors.

//What is the value of the first triangle number to have over five hundred divisors?

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Collections;
using ProjectEuler.Utilities;

namespace ProjectEuler.Problem
{
    public class Problem12 : IProblem
    {

        public void PrintSummary()
        {
            System.Console.WriteLine("Problem 12");
        }

        public void Execute()
        {
            // Number of divisors for the current number
            Int64 numDivisors = 0;
            Int64 number = 0;
            Int64 triangleNumber = 0;

            // Iterate until we have reached a number with 500 divisors
            while (numDivisors <= 500)
            {
                // Increment the number
                ++number;

                // Increment triangle number
                triangleNumber += number;

                // Calculate the number of divisors
                numDivisors = MathUtils.NumDivisors(triangleNumber);
            }

            System.Console.WriteLine(triangleNumber.ToString());
        }
    }
}
