// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using ProjectEuler.Utilities;

namespace ProjectEuler.Problem
{
    public class Problem2 : IProblem
    {
        public void PrintSummary()
        {
            System.Console.WriteLine("Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:");
            System.Console.WriteLine("1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...");
            System.Console.WriteLine("By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.");
        }

        public void Execute()
        {
            // Setup for fibonnaci
            int sum = 2;    // Base value of sum is 2 due to the second seed term
            int a = 1;
            int b = 2;
            int fib = MathUtils.NextFibonacci(a, b);
            while (fib <= 4000000)
            {
                // Add to the sum if it's an even value
                if (MathUtils.IsMultiple(fib, 2) == true)
                {
                    sum += fib;
                }

                // Shift the value of b to a and the value of fib to b
                a = b;
                b = fib;
                fib = MathUtils.NextFibonacci(a, b);
            }

            // Solution!
            System.Console.WriteLine(fib.ToString());
        }
    }
}
